### ISSUE TITLE
Are there any official approaches to this?

### ISSUE THREAD

**Issue by aleksasiriski** [mk-fg/systemd-cgroup-nftables-policy-manager#2]
Hello there, I've been investigating this topic a lot lately and want to achieve something that in the end is similar to your use case. Just came here to ask, if there are any new official ways of doing this? My scenario is the following: disallow all processes to access internet except a proxy systemd service which does some filtering, using nftables. Other services on the system should use the proxy to access the internet.

**Comment by mk-fg** [comment]
Not that I know of, unfortunately, but I haven't looked since initial failure to find any such tool couple years ago.

For specific use-case you have in mind though, don't think you even need this tool - can have nftables init with "deny all" policy on early boot (before network setup), and then have `ExecStartPost=+nft ...` line in that proxy's .service file, allowing access for its cgroup only.
Anything more dynamic and complex would only introduce all sorts of extra failure modes there, I think.

**Comment by aleksasiriski** [comment]
Oh that sounds interesting, are you saying I could do something like this?

```
[Service]
ExecStartPost=/usr/sbin/nft add rule inet filter output cgroupv2 path "/sys/fs/cgroup/system.slice/k3s.service/" accept
ExecStopPost=/usr/sbin/nft delete rule inet filter output cgroupv2 path "/sys/fs/cgroup/system.slice/k3s.service/" accept
```

**Comment by mk-fg** [comment]
Yeah, should be the best way to go about it, I think.

Though dunno if you need to specify mountpoint (netfilter module likely doesn't care if cgroup fs is mounted at all), and might need to specify "level" parameter (though I don't remember why it's there, "man nft" probably knows).

So something like:
```
ExecStartPost=+nft 'add rule inet filter output socket cgroupv2 level 2 "system.slice/k3s.service" accept'
```

Few other changes I've made there:

- Systemd looks up binaries in its PATH these days, so /usr/sbin/nft might not be needed either.
- Single quotes are around whole nft rule to avoid systemd eating double-quotes for its own argument-quoting syntax.
- `ExecStartPost=+...` which I also used above is a special systemd syntax meaning "run this as root, even if service has User=" - might be needed for "nft", unless you start whole thing as root anyway.

**Comment by aleksasiriski** [comment]
Thanks for your help, I might try these some day but currently the situation is fixed for me. Apparently if I use firewalld to deny outbound connections, it does that correctly for all programs on my system and any commands that I use as the user, but k3s ignores it (or at least cilium cni does). In the end, that works for my setup requirements, as I can connect to a proxy pod running in k8s using NodePort.

**Comment by aleksasiriski** [comment]
In case anyone stumbles on this like I did: ended up using this config in `/etc/systemd/system/k3s.services.d/10-network.conf`:

```
[Service]
ExecStartPost=+nft 'insert rule ip filter OUTPUT socket cgroupv2 level 2 "system.slice/k3s.service" counter accept'
ExecStartPost=+nft 'insert rule ip6 filter OUTPUT socket cgroupv2 level 2 "system.slice/k3s.service" counter accept'
ExecStartPost=+sh -c 'while [ ! -d /sys/fs/cgroup/kubepods.slice ]; do sleep 1; done; nft "insert rule ip filter OUTPUT socket cgroupv2 level 2 kubepods.slice counter accept"' &
ExecStartPost=+sh -c 'while [ ! -d /sys/fs/cgroup/kubepods.slice ]; do sleep 1; done; nft "insert rule ip6 filter OUTPUT socket cgroupv2 level 2 kubepods.slice counter accept"' &
ExecStartPost=+sh -c 'while [ ! -d /sys/fs/cgroup/kubepods.slice/kubepods-besteffort.slice ]; do sleep 1; done; nft "insert rule ip filter OUTPUT socket cgroupv2 level 2 kubepods.slice/kubepods-besteffort.slice counter accept"' &
ExecStartPost=+sh -c 'while [ ! -d /sys/fs/cgroup/kubepods.slice/kubepods-besteffort.slice ]; do sleep 1; done; nft "insert rule ip6 filter OUTPUT socket cgroupv2 level 2 kubepods.slice/kubepods-besteffort.slice counter accept"' &
ExecStartPost=+sh -c 'while [ ! -d /sys/fs/cgroup/kubepods.slice/kubepods-burstable.slice ]; do sleep 1; done; nft "insert rule ip filter OUTPUT socket cgroupv2 level 2 kubepods.slice/kubepods-burstable.slice counter accept"' &
ExecStartPost=+sh -c 'while [ ! -d /sys/fs/cgroup/kubepods.slice/kubepods-burstable.slice ]; do sleep 1; done; nft "insert rule ip6 filter OUTPUT socket cgroupv2 level 2 kubepods.slice/kubepods-burstable.slice counter accept"' &

```

Alongside these firewalld rules (TF code):
```terraform
join(" && ", [
      # Allow inbound traffic on all ports from any source (IPv4 and IPv6) - stricter rules are handled by Hetzner Firewall and Cilium Host Firewall
      "firewall-cmd --permanent --add-rich-rule='rule family=ipv4 source address=0.0.0.0/0 accept'",
      "firewall-cmd --permanent --add-rich-rule='rule family=ipv6 source address=::/0 accept'",
      # Set the default drop policy for outbound traffic
      "firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 999 -j DROP",
      "firewall-cmd --permanent --direct --add-rule ipv6 filter OUTPUT 999 -j DROP",
      # Allow established and related connections
      "firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT",
      "firewall-cmd --permanent --direct --add-rule ipv6 filter OUTPUT 0 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT",
      # Drop invalid connections
      "firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 0 -m conntrack --ctstate INVALID -j DROP",
      "firewall-cmd --permanent --direct --add-rule ipv6 filter OUTPUT 0 -m conntrack --ctstate INVALID -j DROP",
      # Allow loopback interface
      "firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 0 -o lo -j ACCEPT",
      "firewall-cmd --permanent --direct --add-rule ipv6 filter OUTPUT 0 -o lo -j ACCEPT",
      # Allow outbound traffic to private IPv4 networks
      "firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 100 -d 10.0.0.0/8 -j ACCEPT",
      "firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 100 -d 172.16.0.0/12 -j ACCEPT",
      "firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 100 -d 192.168.0.0/16 -j ACCEPT",
      # Allow outbound traffic to private IPv6 networks
      "firewall-cmd --permanent --direct --add-rule ipv6 filter OUTPUT 100 -d fc00::/7 -j ACCEPT",
      "firewall-cmd --permanent --direct --add-rule ipv6 filter OUTPUT 100 -d fe80::/10 -j ACCEPT",
      # Allow outbound DNS traffic
      "firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 100 -p udp --dport 53 -j ACCEPT",
      "firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 100 -p tcp --dport 53 -j ACCEPT",
      "firewall-cmd --permanent --direct --add-rule ipv6 filter OUTPUT 100 -p udp --dport 53 -j ACCEPT",
      "firewall-cmd --permanent --direct --add-rule ipv6 filter OUTPUT 100 -p tcp --dport 53 -j ACCEPT",
      # Allow outbound NTP traffic
      "firewall-cmd --permanent --direct --add-rule ipv4 filter OUTPUT 100 -p udp --dport 123 -j ACCEPT",
      "firewall-cmd --permanent --direct --add-rule ipv6 filter OUTPUT 100 -p udp --dport 123 -j ACCEPT",
      # Reload the firewall to apply changes
      "firewall-cmd --reload"
    ]),
```

**Comment by mk-fg** [comment]
Ouch, that looks a lot more complicated than adding one rule after service start.

Might be possible to create/start .slice units in advance, as a Requires= dependency or something, to avoid needing to wait for them via shell loops.
Also wonder if maybe adding a trivial BPFProgram= to .service and .slice above via .conf drop-in to set fwmark on all outgoing packets might allow to avoid needing "nft" commands, to keep all rules in firewalld.

**Comment by aleksasiriski** [comment]
> Ouch, that looks a lot more complicated than adding one rule after service start.

Yeah...

> Might be possible to create/start .slice units in advance, as a Requires= dependency or something, to avoid needing to wait for them via shell loops. Also wonder if maybe adding a trivial BPFProgram= to .service and .slice above via .conf drop-in to set fwmark on all outgoing packets might allow to avoid needing "nft" commands, to keep all rules in firewalld.

If you have any pointers, I would be thankful. Am glad to learn a bit of BPF along the way :) The main problem is that while `system.slice/k3s.service` is created as soon as the service starts, the other ones are created by k8s itself a little later.

**Comment by mk-fg** [comment]
> the other ones are created by k8s itself a little later.

Yeah, guess if it creates these .slice's dynamically via systemd api, with some parameters, then making/requiring empty kubepods.slice unit might be a bad idea. But suspect systemd might still pick-up a drop-in .conf for these.

> If you have any pointers, I would be thankful. Am glad to learn a bit of BPF along the way

I'd think it'd be something along the lines of:
``` c
SEC("cgroup/skb")
int mark_all_packets(struct __sk_buff *skb) {
  skb->mark = 0x123;
  return 1; // pass packet through
}
```

gcc/clang should be able to build those with `-target bpf`, and in my experience ABI there have been stable to the point where cgroup/skb BPF that I've built 5y ago still loads and works for me to this day, and pretty sure these BPFs are portable, i.e. can just copy compiled ones between systems.

Not sure how BPFProgram= works in systemd these days.
I only needed it in "systemd --user" scopes/slices and iirc when I tried it years ago, it didn't work due to lacking permissions (I think kernel had a knob for it, which I definitely have disabled for security reasons), so instead I've been loading BPFs for user-cgroups kinda like nftables rules via something like `sudo bpftool cgroup attach ...` (from a script initializing the .scope).
But probably should work, especially for --system units.

Also not sure if it ultimately makes things simpler, maybe just an option to consider in such scenarios.

**Comment by mk-fg** [comment]
I've just randomly bumped into NFTSet= option in [systemd.resource-control] that does provide simpler and more built-in solution for what this tool does. This was added in systemd-255 released on 2023-12-06, so was likely also available at the time this issue was opened, I just wasn't yet aware of it.

So I think unless using non-systemd distro, or NFTSet= option fails to work for some reason, that should probably be the go-to "official" approach to this, instead of the tool in this repo.

[systemd.resource-control]: https://man.archlinux.org/man/systemd.resource-control.5
